services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: fitness-tracker-backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
    environment:
      - PYTHONPATH=/app
    # profiles: [dev]
    # develop:
    #   watch:
    #     - path: .
    #       action: rebuild

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"
    container_name: fitness-tracker-frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    # profiles: [dev]
    # develop:
    #   watch:

# volumes:
#   data:
#     "/data"
