version: "2.29.1"

services:
  app:
    build: .
    container_name: fitness-tracker
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload  # "python src/main.py"
    ports:
      - 8080:80
    profiles: [dev]
    # volumes:
      # - .:/code  # .:/scr  # .:/app
