
services:
  app:
    build: .
    container_name: fitness-tracker
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload  # "python src/main.py"
    ports:
      - 8080:80
    # volumes:
      # - .:/code  # .:/scr  # .:/app
      # - /Library/CloudStorage/GoogleDrive-gcr84@hotmail.com/My Drive/DATA/fitness-tracker-data:/app/data

# CLI command, 1.st time: docker-compose up --build
# CLI command, without image building: docker-compose up
# Then visit: http://localhost:8080
