version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 8080:80
    develop:
      watch:
        - path: .
          action: rebuild
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    container_name: fitness-tracker
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload  # "python src/main.py"
    profiles: [dev]
    volumes:
      - data:/data
      # - .:/code  # .:/scr  # .:/app
    # secrets:
    #   - 
