---
google_drive_data_path: "/Users/<USER>/Library/CloudStorage/GoogleDrive-<EMAIL>/My Drive/DATA/fitness-tracker-data"
real_workout_database: "<GOOGLE_DRIVE_DATA_PATH>/<ATHLETE>/db.json"
real_disciplines_database: "<GOOGLE_DRIVE_DATA_PATH>/<ATHLETE>/real_disciplines.json"
simulated_workout_database: "<GOOGLE_DRIVE_DATA_PATH>/sim_db.json"
real_weight_table: "weight_training_log"
real_disciplines_table: "disciplines_log"
simulated_weight_table: "weight_training_log"
training_catalogue: "src/helpers/muscles_and_exercises.yaml"
