[tool.poetry]
name = "fitness-tracker"
version = "0.1.0"
description = "Full stack fitness tracking application"
authors = ["Gustav Rasmussen"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.10"
tinydb = "^4.5.2"
pyyaml = "^5.4.1"
pandas = "^1.3.5"
mypy = "^0.931"
yamllint = "^1.26.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^3.9.2"
# sphinx = "^"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
