[tool.poetry]
name = "fitness-tracker"
version = "0.1.0"
description = ""
authors = ["Gustav Collin Rasmussen"]

[tool.poetry.dependencies]
behave = "^1.2.6"
fastapi = "^0.78.0"
Faker = "^15.3.1"
flake8 = "^4.0.1"
mypy = "^1.2"
pandas = "^2.0.0"
pydantic = "^1.9.1"
python = "^3.11.2"
PyYAML = "^6.0"
pytest = "^7.1.2"
pytest-cov = "^4.0.0"
Sphinx = "^5.0.2"
tinydb = "^4.7.0"
uvicorn = "^0.18.2"
watchfiles = "^0.15.0"
wily = "^1.24.0"
yamllint = "^1.26.3"
ruff = "^0.0.240"
athleteprofiler = "^0.1.1"
matplotlib = "^3.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
