[tool.poetry]
name = "fitness-tracker"
version = "0.1.0"
description = ""
authors = ["Gustav Collin Rasmussen"]

[tool.poetry.dependencies]
athleteprofiler = "^0.1.1"
behave = "^1.2.6"
fastapi = "^0.100.0"
Faker = "^19.1.0"
flake8 = "^6.0.0"
matplotlib = "^3.7.2"
mypy = "^1.4"
pandas = "^2.0.3"
pydantic = "^2.0.0"
python = "^3.11.4"
PyYAML = "^6.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
ruff = "^0.0.278"
seaborn = "^0.12.2"
Sphinx = "^7.0.1"
tinydb = "^4.8.0"
uvicorn = "^0.23.0"
watchfiles = "^0.19.0"
wily = "^1.24.2"
yamllint = "^1.32.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
