openapi: 3.1.0
info:
  title: Your API Title
  description: Your API Description
  version: 0.1.0
paths:
  /:
    get:
      summary: Main Page
      description: Returns a greeting message for the application.
      operationId: main_page__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /data:
    get:
      summary: Get Data
      description: Show data
      operationId: get_data_data_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /dates:
    get:
      summary: Get Dates
      description: Returns a list of all workout dates.
      operationId: get_dates_dates_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                title: Response Get Dates Dates Get
  /dates_and_splits:
    get:
      summary: Get Dates And Splits
      description: Returns a dictionary of workout dates and their corresponding muscle
        groups.
      operationId: get_dates_and_splits_dates_and_splits_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /dates/{date}:
    get:
      summary: Describe Workout
      description: Returns a dictionary describing the workout for the given date.
      operationId: describe_workout_dates__date__get
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          title: Date
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /{date}/exercises/{exercise}:
    get:
      summary: Show Exercise
      description: Returns a list of sets and reps for the given exercise and date.
      operationId: show_exercise__date__exercises__exercise__get
      parameters:
      - name: exercise
        in: path
        required: true
        schema:
          type: string
          title: Exercise
      - name: date
        in: path
        required: true
        schema:
          type: string
          title: Date
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                title: Response Show Exercise  Date  Exercises  Exercise  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
