---
coverage:
  range: 0..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 40%
        threshold: 10%
    patch:
      default:
        target: 10%
        threshold: 10%
