[default]
# DEBUG = true
# env_file = ".env"

GOOGLE_DRIVE_DATA_PATH = "@jinja /Users/{{ env.USER }}/Library/CloudStorage/GoogleDrive-{{ env.EMAIL }}/My Drive/DATA/fitness-tracker-data"
img_path = "@jinja {{ this.google_drive_data_path }}/{{ env.ATHLETE }}/img/"
real_workout_database = "@jinja {{ this.google_drive_data_path }}/{{ env.ATHLETE }}/<YEAR>_workouts.yml"
real_disciplines_database = "@jinja {{ this.google_drive_data_path }}/{{ env.ATHLETE }}/real_disciplines.json"
simulated_workout_database = "@jinja {{ this.google_drive_data_path }}/sim_db.yml"
real_weight_table = "weight_training_log"
real_disciplines_table = "disciplines_log"
simulated_weight_table = "weight_training_log"
training_catalogue = "src/utils/muscles_and_exercises.yaml"
workout_programs = "docs/project_docs/Workout-Programs/workout_programs.yml"
# VERSION = "0.0.1"

# [development]
# key2 = "development_value"

# [production]
# key2 = "production_value"

[validator]
GOOGLE_DRIVE_DATA_PATH = {must_exist=true}
