name: Docker Image Workflow

on:
  workflow_call:
    inputs:
      image-name:
        description: "Docker Image Name"
        required: true
        type: string
      image-tag:
        description: "Docker Image Tag"
        required: true
        type: string
      dockerhub-username:
        description: "DockerHub Username"
        required: false
        type: string
        # default: gustavrasmussen
      github-owner:
        description: "GitHub Owner (for GitHub Packages)"
        required: false
        type: string
        # default: "TheNewThinkTank"

jobs:
  build_scan_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Log in to DockerHub
        if: inputs.dockerhub-username
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Packages
        if: inputs.github-owner
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ inputs.github-owner }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
              --build-arg USER=${{ secrets.USER }} \
              --build-arg ATHLETE=${{ secrets.ATHLETE }} \
              --build-arg EMAIL=${{ secrets.EMAIL }} \
              --build-arg ALTERNATIVE_EMAIL=${{ secrets.ALTERNATIVE_EMAIL }} \
              -t ${{ inputs.image-name }}:${{ inputs.image-tag }} .
        # docker build -t ${{ inputs.image-name }}:${{ inputs.image-tag }} .

      # # Build the Docker image
      # - name: Build Docker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: false  # Do not push the image
      #     tags: gustavrasmussen/${{ inputs.image-name }}:${{ inputs.image-tag }}
      #     build-args: |
      #       USER=${{ secrets.USER }}
      #       ATHLETE=${{ secrets.ATHLETE }}
      #       EMAIL=${{ secrets.EMAIL }}
      #       ALTERNATIVE_EMAIL=${{ secrets.ALTERNATIVE_EMAIL }}

      - name: Scan Docker image for vulnerabilities
        uses: anchore/scan-action@v7
        with:
          image: ${{ inputs.image-name }}:${{ inputs.image-tag }}
          fail-build: false

      - name: Push to DockerHub
        if: inputs.dockerhub-username
        run: |
          docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.dockerhub-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          docker push ${{ inputs.dockerhub-username }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

      - name: Push to GitHub Packages
        if: inputs.github-owner
        run: |
          docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} ghcr.io/${{ inputs.github-owner }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          docker push ghcr.io/${{ inputs.github-owner }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
