---
name: Fitness Tracker Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

# env:
#   IMAGE_NAME: "fitness-tracker"

jobs:
  qualify_code:
    uses: ./.github/workflows/qualify_code.yml
    with:
      google_drive_data_path: "data"

  docker_image_workflow:
    needs: qualify_code
    uses: ./.github/workflows/docker_image.yml
    with:
      image-name: fitness-tracker  # ${{ env.IMAGE_NAME }}
      image-tag: latest
      # dockerhub-username: gustavrasmussen  # Optional, if pushing to DockerHub
      github-owner: thenewthinktank  # Optional, if pushing to GitHub Packages

  # deploy_to_AWS_ECR:
  #   needs: qualify_code
  #   uses: ./.github/workflows/aws_ecr.yml
  #   with:
  #     aws-region: eu-central-1
  #     ecr-repository: fitness-tracker
  #     image-tag: ft-image
