---
name: Fitness Tracker Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHONVERSION: 3.11
#   IMAGE_NAME: "fitness-tracker"

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      PYTHONVERSION: ${{ env.PYTHONVERSION }}
    steps:
      - run: echo "Exposing env vars"

  qualify_code:
    needs: vars
    uses: ./.github/workflows/job_qualify_code.yml
    with:
      PYTHONVERSION: ${{ needs.vars.outputs.PYTHONVERSION }}
      google_drive_data_path: "data"
    secrets:
      ATHLETE: ${{ secrets.ATHLETE }}

  # docker_image_workflow:
  #   needs: qualify_code
  #   uses: ./.github/workflows/job_docker_image.yml
  #   with:
  #     image-name: fitness-tracker  # ${{ env.IMAGE_NAME }}
  #     image-tag: latest
  #     # dockerhub-username: gustavrasmussen  # Optional, if pushing to DockerHub
  #     github-owner: thenewthinktank  # Optional, if pushing to GitHub Packages

  # deploy_to_AWS_ECR:
  #   needs: qualify_code
  #   uses: ./.github/workflows/job_aws_ecr.yml
  #   with:
  #     aws-region: eu-central-1
  #     ecr-repository: fitness-tracker
  #     image-tag: ft-image
